### ISSUE TITLE
Setup some code guidelines through editorconfig

### ISSUE THREAD

**Issue by Baklap4** [OkGoDoIt/OpenAI-API-dotnet#71]
Lately we've been doing a lot with ChatGPT, and as this is one of the popular ways to communicate with OpenAI it'd be nice to standardize and enforce the codestyle. This makes the code:
1. More readable
2. Easier to work with
3. Maintainable when multiple people work on it

Microsoft gives a great example of these codeconventions for naming, what to use etc. : https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions

## Todo

- [ ] Add editorconfig
- [ ] fix the warnings
- [ ] Remove current Pragmas/ignores and fix the underlying problem
- [ ] Enable code analysis
- [ ] Optional: Treat warnings as errors
- [ ] Introduce CI which fails when warnings are found
