### ISSUE TITLE
Setup GH Actions CI/CD

### ISSUE THREAD

**Issue by Baklap4** [OkGoDoIt/OpenAI-API-dotnet#72]
Each program/library in 2023 should have some form of automation to ensure stuff builds and can be deployed without manually opening up VS(code) and build the project.

GH offers a feature called [Github Actions](https://docs.github.com/en/actions) which does exactly that. Automate the stuff like builds and create releases.

This ensures quality, and can execute your tests automaticly.

## Todo 

- [ ] Add a GH Workflow
    - [ ] Build the library
        - [ ] Static analysis
    - [ ] Test the library
    - [ ] Deploy the library
    - [ ] Create release notes
- [ ] Think of a versioning system, preferably [semver](https://semver.org/)

**Comment by sannae** [comment]
Hi! First-time contributor, please be understanding... 😅 
I'd like to help on this issue, if no one is already working on it - I have a little experience with GitHub Actions CI/CD, and I'd like to improve specifically in the context of .NET applications.
Which tool would you suggest for performing static analysis? Something like the [CodeQL action](https://github.com/github/codeql-action)?

**Comment by Baklap4** [comment]
Basicly for dotnet there are a couple of steps:
* `dotnet restore` - this restores the nuget dependencies
* `dotnet build -c Release` - this command builds the project and outputs the files to a folder in Release mode
* `dotnet test` - Runs the unittest suite
* `dotnet publish -c Release` - This commands publishes a nuget package which can be automaticly uploaded to nuget.org

For static analysis i'd first rely on the static analysis from dotnet itself which is already pretty good and with NRT enabled even better. This can be done by setting up some `csproj` properties combined with `TreatWarningsAsErrors`. Aside from that there's the code conventions mentioned in #71 this is done through an EditorConfig file in which we can specify what we treat as Suggestion, info, warning, error. But someone should first finalize that + apply it to the codebase i think.

**Comment by sannae** [comment]
Thanks for the tips! I'd try to set up a CI/CD workflow without static analysis, then maybe integrate it along the way. What do you think?
